#!/bin/bash -ex
echo 'github上のmasterブランチをisucon-aのみにreleaseします!'

mkdir -p /tmp/isucon-release
cd /tmp/isucon-release
if [ ! -d "/tmp/isucon-release/isucon2018" ]; then
  git clone git@github.com:quipper/isucon2018.git
fi
cd isucon2018
git pull --rebase

rsync -az -e ssh --delete . isucon@isucon-a:torb
# rsync -az -e ssh --delete . isucon@isucon-b:torb
# rsync -az -e ssh --delete . isucon@isucon-c:torb
# add b and c

ssh isucon@isucon-a 'cd torb && exec ./script/update'
# ssh isucon@isucon-b 'cd torb && exec ./script/update'
# ssh isucon@isucon-c 'cd torb && exec ./script/update'
